name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t storybook-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag storybook-app ${{ secrets.DOCKER_HUB_USERNAME }}/storybook-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/storybook-app:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 194.147.142.75
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/storybook-app:latest
            docker stop storybook-container || true
            docker rm storybook-container || true
            docker run -d -p 80:6006 --name storybook-container ${{ secrets.DOCKER_HUB_USERNAME }}/storybook-app:latest
